### ISSUE TITLE
GPU Temperature

### ISSUE THREAD

**Issue by KonomiKitten** [anderskm/gputil#13]
It would be nice if we were able to see the temperature of the GPU as well.

**Comment by anderskm** [comment]
Yep! :-)
I've taken a quick look at it, and it should be possible as long as the GPU supports it.
Just need to include `temperature.gpu` in the nvidia-smi query. I'll have a look at this week.

**Comment by anderskm** [comment]
@KonomiKitten No worries :-)
I have added a new commit (https://github.com/anderskm/gputil/commit/c3d1f6d4f9ee34df3e0df7caaa4365372b99c839), which includes the temperature.
