### ISSUE TITLE
nvidia-smi comes with NVIDIA drivers, and not CUDA

### ISSUE THREAD

**Issue by stas00** [anderskm/gputil#16]
This is very useful module! Thank you!

I have a small suggestion wrt README.md which is somewhat misleading, as it says:

> CUDA GPU with latest CUDA driver installed. GPUtil uses the program nvidia-smi to get the GPU status of all available CUDA GPUs. nvidia-smi should be installed automatically, when you install your CUDA driver.

But according to: https://developer.nvidia.com/nvidia-system-management-interface

> NVIDIA-smi ships with NVIDIA GPU display drivers on Linux, and with 64bit Windows Server 2008 R2 and Windows 7. 

so I think the correct description needs to replace CUDA to NVIDIA drivers.

The reason I find it's important, is because for example pytorch started shipping its own CUDA libraries and you no longer need to install CUDA-system wide. Yet, the user will still have nvidia-smi if they installed the NVIDIA driver, but not with pytorch. And currently your doc implies that a user must have CUDA installed to have nvidia-smi, which is not so. 

I hope my communication was clear.

Thank you.

**Comment by anderskm** [comment]
@stas00 Thank you for pointing that out!
I completely agree, that it is an important distinction.
I'll make an update later today :-)
