### ISSUE TITLE
ImportError: No module named GPUtil

### ISSUE THREAD

**Issue by fiorano10** [anderskm/gputil#29]
After installing via pip, I keep getting this error

**Comment by anderskm** [comment]
@fiorano10 Could you provide some more information?
Operating system? Python version? Do you have multiple versions of Python installed?

**Comment by fiorano10** [comment]
@anderskm Tried on 16.04 and 18.04, Python 2.7 and 3.5 are both installed

**Comment by Hyperclaw79** [comment]
Could reproduce the same on v1.4.0 on Py3.7.7
Tried to run it on Google Colab and was hit by the ModuleNotFound exception.
Edit: Disregard, seems like a Python path issue on Colab

**Comment by whria78** [comment]
I solved by installing pip3 install gputil  (NOT sudo pip3 install gputil). No "sudo"
