### ISSUE TITLE
FileNotFoundError shows up whenever I try to use this package

### ISSUE THREAD

**Issue by dherrada** [anderskm/gputil#8]
This is the error it gives me whenever I try to run it:

GPUtil 1.3.0
Traceback (most recent call last):
  File "demo_GPUtil.py", line 10, in <module>
    GPU.showUtilization()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\Lib\site-packages\GPUtil\GPUtil.py", line 193, in showUtilization
    GPUs = getGPUs()
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\Lib\site-packages\GPUtil\GPUtil.py", line 64, in getGPUs
    p = Popen(["nvidia-smi","--query-gpu=index,uuid,utilization.gpu,memory.total,memory.used,memory.free,driver_version,name,gpu_serial,display_active,display_mode", "--format=csv,noheader,nounits"], stdout=PIPE)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\dylan\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by dherrada** [comment]
Also, I have a "NVIDIA GeForce GTX 1060 with Max-Q Design" with 8 GB VRAM

**Comment by anderskm** [comment]
Make sure, that your PATH environment variable also covers the folder containing `nvidia-smi`.
In Ubuntu, I think it is automatically added, when you install/update your CUDA drivers. But that might not be the case on Windows.
If you open a command window in Windows and call `nvidia-smi` directly, do you get an error or does it produce an output with the status of your GPU(s)?
On my windows partition, `nvidia-smi.exe` is located in "C:\Program Files\NVIDIA Corporation\NVSMI"
However, by default, it is not part of my PATH and when calling `nvidia-smi` from any other folder produces an error. See the image below.

I hope this helps :-)

![image](https://user-images.githubusercontent.com/4207617/43774763-8b3b6de8-9a4a-11e8-8c5f-25ca3b99c137.png)

**Comment by nyanye** [comment]
I think a lot of Windows user could struggle to this kind of FileNotFoundError or simply 'PATH' issues and opened pull-request #17 to figure it out :)

**Comment by anderskm** [comment]
Thank you @nyanye .
I'm closing this issue, as I have merged your solution in pull-request #17.
